# Recipe in rattler-build format.
# See https://prefix-dev.github.io/rattler-build/latest/

context:
  version: "0.9.0"

package:
  name: openjd-adaptor-runtime
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/o/openjd-adaptor-runtime/openjd_adaptor_runtime-${{ version }}.tar.gz
  sha256: a2a117b23df4e7fa31360b4572528ecabeeed190f5a4c51177560d401df79704
  patches:
    - 0001-Remove-version-hook.patch

build:
  number: 0
  script:
    - python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python
    - pyyaml >=6.0,<7.dev0
    - jsonschema >=4.17.0,<5.0
    - ${{ "pywin32 >=307" if win }}

tests:
- python:
    imports:
    - openjd.adaptor_runtime
    - openjd.adaptor_runtime_client
- requirements:
    run:
      - pip
  script:
  - pip check

about:
  summary: A python library for building adaptors that integrate applications with Open Job Description jobs.
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
