# Recipe in rattler-build format.
# See https://prefix-dev.github.io/rattler-build/latest/

context:
  version: "4.3.0"
  major_minor_version: "4.3"

package:
  name: blender
  version: ${{ version }}

source:
  - if: linux
    then:
      url: https://download.blender.org/release/Blender${{ major_minor_version }}/blender-${{ version }}-linux-x64.tar.xz
      sha256: 6264ff4cf50baf6be6091a28d3c29cf25dc38d8daa3082874ce94d520d3e6ab6
      target_directory: blender
  - if: win
    then:
      url: https://download.blender.org/release/Blender${{ major_minor_version }}/blender-${{ version }}-windows-x64.zip
      sha256: 68777b84f1e8970859428b3c4bc8e8675e8322b19e1566e0a90d575d00d257ac
      target_directory: blender

build:
  number: 0
  # These build options for repackaging an application
  # https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html
  prefix_detection:
    ignore_binary_files: True
  dynamic_linking:
    binary_relocation: False
    missing_dso_allowlist:
    - "**"

tests:
  - script:
    - blender -h

about:
  homepage: https://www.blender.org/
  license: GPL-3.0
  summary: >
    Blender is the free and open source 3D creation suite. It supports the entirety of
    the 3D pipeline—modeling, rigging, animation, simulation, rendering, compositing
    and motion tracking, even video editing and game creation.
