{% set version_vray = "62002" %}
{% set version_maya = "2025" %}
{% set version = version_maya + "." + version_vray %}

package:
  name: maya-vray
  version: {{ version }}

source:
    url: archive_files/vray_adv_{{ version_vray }}_maya{{ version_maya }}_rhel8
    sha256: 6bde52e650e97bacaeae12039f48f57699b9fb41361fa646cd92b52efd1d6e9e
build:
  number: 0
  binary_relocation: False
  detect_binary_files_with_prefix: False
  # V-Ray for Maya is built to be relocatable, so can ignore the warnings about DSOs.
  missing_dso_whitelist:
  - "*"

about:
  home: https://www.chaos.com/vray/maya
  doc_url: https://docs.chaos.com/display/VMAYA
  license: Commercial
  summary: |
    V-Ray is a 3D photorealistic ray-traced rendering plug-in.
    V-Ray for Maya is a 3D rendering plugin for Maya that's used to create visual effects and animations for film, television, and other industries.