# Recipe in conda-build format.
# See recipe.yaml for the recipe in rattler-build format.

{% set name = "maya-openjd" %}
{% set version = "0.14.4" %}

package:
  name: {{ name }}
  version: {{ version }}

# This source reference uses the source archive published to PyPI
source:
 url: https://pypi.io/packages/source/d/deadline-cloud-for-maya/deadline_cloud_for_maya-{{ version }}.tar.gz
 sha256: 9b86a6c02df800ed3e69a3094c0f7d2aaa8b07304af34068fc41e2e14313268e
 patches:
   - 0001-Remove-version-hook.patch

# # This source reference uses git to retrieve the tag for the specified version. You can modify
# # the git_url and git_rev to point to a branch in your own fork of the project.
# source:
#   git_url: https://github.com/aws-deadline/deadline-cloud-for-maya.git
#   git_rev: {{ version }}

build:
  entry_points:
    - maya-openjd = deadline.maya_adaptor.MayaAdaptor:main
    - MayaAdaptor = deadline.maya_adaptor.MayaAdaptor:main
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    # For the variant config file in deadline-cloud.yaml to work, python must not specify a version here.
    - python
    - hatchling
    - hatch-vcs
    - pip
  run:
    # For the variant config file in deadline-cloud.yaml to work, python must not specify a version here.
    - python
    - deadline ==0.49.*
    - openjd-adaptor-runtime ==0.8.*

test:
  imports:
    - deadline.maya_adaptor
  commands:
    - pip check
    - maya-openjd --help
  requires:
    - pip

about:
  summary: AWS Deadline Cloud for Maya
  dev_url: https://github.com/aws-deadline/deadline-cloud-for-maya
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
