# Recipe in conda-build format.
# See recipe.yaml for the recipe in rattler-build format.

{% set name = "deadline" %}
{% set version = "0.49.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deadline-{{ version }}.tar.gz
  sha256: 30ff5c2bf3c9e0b9c42b777661ed470cbc6333d877cf386f9c5c31918844a553
  patches:
    - 0001-Remove-version-build-hook.patch

build:
  skip: true  # [py<38]
  entry_points:
    - deadline-dev-gui = deadline.client.cli.deadline_dev_gui_main:main
    - deadline = deadline.client.cli:main
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python
    - boto3 >=1.34.75
    - click >=8.1.7
    - pyyaml >=6.0
    - typing-extensions >=4.8
    - python-xxhash >=3.4,<3.6
    - jsonschema ==4.17.*
    - pywin32 >=307,<309  # [win]
    - qtpy ==2.4.*

test:
  imports:
    - deadline
  commands:
    - pip check
    - deadline --help
    - python -m deadline --help
  requires:
    - pip

about:
  summary: Multi-purpose library and command line tool that implements functionality to support applications using AWS Deadline Cloud.
  dev_url: https://github.com/aws-deadline/deadline-cloud
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
