# Recipe in rattler-build format.
# See https://prefix-dev.github.io/rattler-build/latest/

context:
  version: "0.49.3"

package:
  name: deadline
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/d/deadline/deadline-${{ version }}.tar.gz
  sha256: 30ff5c2bf3c9e0b9c42b777661ed470cbc6333d877cf386f9c5c31918844a553
  patches:
    - 0001-Remove-version-build-hook.patch

build:
  number: 0
  script:
    - python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python
    - boto3 >=1.34.75
    - click >=8.1.7
    - pyyaml >=6.0
    - typing-extensions >=4.8
    - python-xxhash >=3.4,<3.6
    - jsonschema 4.17.*
    - qtpy 2.4.*
    - ${{ "pywin32 >=307,<309" if win }}

tests:
- python:
    imports:
      - deadline
      - deadline.client
      - deadline.job_attachments
- requirements:
    run:
      - pip
  script:
  - pip check
  - deadline --help
  - python -m deadline --help

about:
  summary: Multi-purpose library and command line tool that implements functionality to support applications using AWS Deadline Cloud.
  homepage: https://github.com/aws-deadline/deadline-cloud
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
